# Here you define the your specific configuration for the area of interest, e.g. the bounding box, the name of the area (used as prefix for input and output files), paths to input and output data, etc. 

area_name: Rastatt

bbox_wgs84:
  left: 8.084
  right: 8.375
  top: 48.916
  bottom: 48.788

crs_proj_out: EPSG:25832  # target CRS for POIs output; should match the coordinate system used by the model / the zones file (OSM source CRS is always EPSG:4326 = GPS coordinates from OSM (WGS84))

exclude_osm_ids:
  - id: 999999999 # dummy, no actual ID to exclude in this sample area

percentile_imputation: 0.15 # If a POI has no area information but area is required for attractiveness calculation for this category, the area is imputed with the this percentile of the areas of all POIs of this category that have area information


paths: # you may use absolute or relative paths; for relative paths, the base path is the current working directory when running the script
  osm_download_url: https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf  # PBF is auto-downloaded to osm_raw_base if missing; remove this line to skip auto-download
  osm_raw_base: data/osm-raw/germany-240101
  filter_dir: config/filters/DE
  osm_filtered_dir: data/osm-filtered
  buildings_input: data/osm-filtered/Rastatt_Buildings.osm
  pois_root_dir: data/pois
  pois_dir_name: Export_Points_Rastatt
  zones_file: data/rastatt_example_zones_25832.geojson
  attractiveness_output_root: data/attractiveness_rastatt_example
  attractiveness_output_sub_attractiveness: attractiveness
  attractiveness_factors_json: config/locale/attractiveness_factors_DE_sample.json
  pois_config: config/locale/OSM2POIs_config_DE.yaml

eval:
  attractiveness_maps:
    zone_types: ["1", "2", "3"] # If empty or omitted, all zone types from the zones file are processed.
    grid_cellsize_m_default: 1000 # Default regular-grid cell size in meters.
    grid_cellsize_m_by_type: # Optional per-zone-type overrides for regular-grid cell size in meters.
      "1": 1000
      "2": 2000
      "3": 5000
    make_html_maps: false # Whether to create HTML maps with the attractiveness values for visual inspection. This requires several further packages to be installed, as well as Pandoc.